name: Build Natives

on:
  workflow_call:

env:
  LIB_NAME: highs
  LIB_VERSION: v1.12.0
  REPOSITORY: ERGO-Code/HiGHS
  METIS_REPOSITORY: galabovaa/METIS
  METIS_BRANCH: 521-ts

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - &checkout_lib
        uses: actions/checkout@v5
        with:
          repository: ${{ env.REPOSITORY }}
          ref: ${{ env.LIB_VERSION }}
      - &checkout_patches
        uses: actions/checkout@v5
        with:
          sparse-checkout: patches
          path: this-repo
      - &checkout_metis
        uses: actions/checkout@v5
        with:
          repository: ${{ env.METIS_REPOSITORY }}
          ref: ${{ env.METIS_BRANCH }}
          path: metis
      - uses: ./this-repo/.github/actions/install-openblas
      - name: Build METIS
        shell: bash
        run: |
          cd metis
          cmake -DGKLIB_PATH=./GKlib -DCMAKE_INSTALL_PREFIX=../metis-installation -DCMAKE_BUILD_TYPE=Release \
            -G "Unix Makefiles" -S ./ -B ./build
          cmake --build ./build
          cmake --install ./build
      - name: Build
        shell: bash
        run: |
          git apply this-repo/patches/*.patch
          cmake -DHIGHSINT64=ON -DJAVA=ON -DHIPO=ON -DMETIS_ROOT=metis-installation -DCMAKE_BUILD_TYPE=Release \
            -G "Unix Makefiles" -S ./ -B ./build
          cmake --build ./build --target highs
      - name: Upload library
        uses: actions/upload-artifact@v5
        with:
          name: lib${{ env.LIB_NAME }}.so
          path: build/lib/lib${{ env.LIB_NAME }}.so

  build-windows:
    runs-on: windows-latest
    steps:
      - *checkout_lib
      - *checkout_patches
      - *checkout_metis
      - uses: ./this-repo/.github/actions/install-openblas
      - name: Build METIS
        shell: bash
        run: |
          cd metis
          cmake -DGKLIB_PATH=./GKlib -DCMAKE_INSTALL_PREFIX=../metis-installation -DCMAKE_BUILD_TYPE=Release \
            -G "Visual Studio 17 2022" -S ./ -B ./build
          cmake --build ./build --config Release
          cmake --install ./build
      - name: Build
        shell: bash
        run: |
          git apply this-repo/patches/*.patch
          cmake -DHIGHSINT64=ON -DHIGHS_NO_DEFAULT_THREADS=ON -DJAVA=ON -DHIPO=ON -DMETIS_ROOT=metis-installation \
            -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows \
            -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022" -S ./ -B ./build
          cmake --build ./build --config Release --target highs
      - name: Upload library
        uses: actions/upload-artifact@v5
        with:
          name: ${{ env.LIB_NAME }}.dll
          path: build/Release/bin/${{ env.LIB_NAME }}.dll

  build-macos:
    runs-on: macos-latest
    steps:
      - *checkout_lib
      - *checkout_patches
      - *checkout_metis
      - name: Build
        shell: bash
        run: |
          git apply this-repo/patches/*.patch
          cmake -DHIGHSINT64=ON -DJAVA=ON -DCMAKE_BUILD_TYPE=Release -G Xcode -S ./ -B ./build
          cmake --build ./build --config Release --target highs
      - name: Upload library
        uses: actions/upload-artifact@v5
        with:
          name: lib${{ env.LIB_NAME }}.dylib
          path: build/Release/lib/lib${{ env.LIB_NAME }}.dylib
